version: '3.8'

services:
  # Service Backend (Laravel) - Avec Scaling & Rolling Update
  backend:
    build: ./backend
    # Suppression de container_name pour permettre l'auto-scaling
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    ports:
      - "8000-8010:8000"
    depends_on:
      - db
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Service Frontend (React) - Avec Scaling & Rolling Update
  frontend:
    build: ./frontend
    # Suppression de container_name
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000-3005:5173"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first

  # Base de données (Port externe 3307)
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: evaluation_sn
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Monitoring - Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_eval
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Monitoring - Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_eval
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  # Collecteur de métriques système (Port externe 9101)
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter_eval
    ports:
      - "9101:9100"

  # Collecteur de métriques des conteneurs Docker
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  db_data:
  grafana_data: